### ISSUE TITLE
Channel support

### ISSUE THREAD

**Issue by spoetnik** [tvdstaaij/telegram-history-dump#1]
Telegram introduces channels a few weeks ago:
https://telegram.org/blog/channels

telegram-cli support this feature in the 'testing' branche.

It would be nice to have a backup of channels to. Any chance this gets implemented?

**Comment by tvdstaaij** [comment]
Thanks for the heads-up, I'll definitely take a look at it. If it's possible to request history for channels and the telegram-cli support is good enough then I should be able to support it in this script as well.

**Comment by tvdstaaij** [comment]
Telegram-cli support is looking good, like I expected it wasn't too hard to implement on my side. Can you check whether it works for you as well?

**Comment by spoetnik** [comment]
Sweet! It works. Thanks for the quick integration!
