### ISSUE TITLE
Fails with latest telegram-cli

### ISSUE THREAD

**Issue by giomasce** [tvdstaaij/telegram-history-dump#19]
`telegram-history-dump.rb` fails with latest `telegram-cli`. The error is

```
$ ./telegram-history-dump.rb 
I, [2016-04-26T14:40:55.234242 #8579]  INFO -- : Attaching to telegram-cli control socket at localhost:9009
I, [2016-04-26T14:40:55.346012 #8579]  INFO -- : Skipping 0 dialogs: (none)
I, [2016-04-26T14:40:55.346120 #8579]  INFO -- : Backing up 57 dialogs: [omissis]
I, [2016-04-26T14:40:55.365495 #8579]  INFO -- : Dumping "user#3417111" (range 1-100)
/home/giovanni/software/telegram/telegram-history-dump/dumpers/lib/dumper_interface.rb:39:in `>': comparison of String with 14 failed (ArgumentError)
	from /home/giovanni/software/telegram/telegram-history-dump/dumpers/lib/dumper_interface.rb:39:in `msg_fresh?'
	from ./telegram-history-dump.rb:84:in `block in dump_dialog'
	from ./telegram-history-dump.rb:67:in `reverse_each'
	from ./telegram-history-dump.rb:67:in `dump_dialog'
	from ./telegram-history-dump.rb:273:in `block in <main>'
	from ./telegram-history-dump.rb:269:in `each'
	from ./telegram-history-dump.rb:269:in `each_with_index'
	from ./telegram-history-dump.rb:269:in `<main>'
```

It works correctly with commit 160231b of `telegram-cli`. I did not have time to find the precise commit that makes it fail. I'm trying on a up-to-date Debian sid system.

**Comment by tvdstaaij** [comment]
I released [url=https://github.com/tvdstaaij/telegram-history-dump/releases/tag/v2.1.0-beta.1]v2.1.0 beta1[/url] about two weeks ago to deal with incompatible telegram-cli changes since 160231b and I tested against 6547c0b, which is the current head revision. But I assume you're using c1fcf92 of telegram-history-dump already. It's pretty likely you've found a problem with this beta, I'll see if I can reproduce the issue.

**Comment by giomasce** [comment]
Yes, I am using https://github.com/tvdstaaij/telegram-history-dump/commit/c1fcf92d6e141e189f21407d3bd781e9a29d20eb.

**Comment by giomasce** [comment]
Thanks to the `bisect` tool, I determined that the first bad commit is ef1e76bf0c81a599d6b27b7a7bff7dd635b85fa2 and the last good one is 8fe867943d8c7981a9faafb1d943fdcdb52162c3. I could not test the commit in between, because compilation fails on my computer.

**Comment by tvdstaaij** [comment]
I can't reproduce this myself but I have an idea of what might be going wrong based on the stack trace.  Do you have a `progress.json` file in your telegram-history-dump output directory that was created before you upgraded telegram-cli? 

After the above commit it is no longer be assumed that message IDs are always strings. I'm not entirely sure why it is not a string in your case, but having an older progress file in combination with having a lot of messages in a very short timespan could be a cause. If this is the case I recommend deleting your progress.json once to create a fresh one with the new id format.

**Comment by giomasce** [comment]
My `progress.json` is made like this:

```
{
  "dumper": "json",
  "last_modified": "2016-04-27T08:32:49+00:00",
  "dialogs": {
    "9790724": {
      "newest_id": 30,
      "newest_date": 1393621424,
      "dumper_state": {
        "outfile": "json/Contact_Name.jsonl"
      }
    }
}
```

I omitted other `dialogs` element and anonymized this one. So yes, it appears that IDs are numbers and not strings. I do not know why.

**Comment by giomasce** [comment]
And I confirm that your last patch fixes the problem for me.
