### ISSUE TITLE
 undefined method 'each' when dumping supergroup as channels

### ISSUE THREAD

**Issue by olithraz** [tvdstaaij/telegram-history-dump#27]
Read over the issues surrounding supergroups, used both the main branch and the dev branch you recommended. Doesn't seem to be an issue on the telegram-cli side of things anyway but I wanted to rule that out.

When trying to dump my group, I get the following:

    brandon@LINUX:~/telegram-history-dump$ ruby telegram-history-dump.rb

    I, [2016-06-28T21:45:20.620050 #28188]  INFO -- : Attaching to telegram-cli control socket at localhost:9009

    telegram-history-dump.rb:161:in 'backup_target?': undefined method 'each' for "SuperGroup":String (NoMethodError)

        from telegram-history-dump.rb:268:in 'block in <main>'

        from telegram-history-dump.rb:250:in 'each'

        from telegram-history-dump.rb:250:in '<main>'

    brandon@LINUX:~/telegram-history-dump$

I used the script perfectly for dumping a single conversation and tested with a normal group which worked fine. 

Here is my config:
    ---

      backup_users: [
    null
      ]
    
      backup_groups: [
    null
      ]
    
      backup_channels: SuperGroup

Let me know if I am just missing something or if you need any more debug info.

**Comment by tvdstaaij** [comment]
These settings must be an array of strings, so it should be `backup_channels: ['SuperGroup']`.

**Comment by olithraz** [comment]
Ah yep there we go thank you much! Totally overlooked it since the other two had the syntax there and my lack of familiarity with ruby. Thanks!
