### ISSUE TITLE
Can't dump with test branch of tg-cli

### ISSUE THREAD

**Issue by Humans-Huddle** [tvdstaaij/telegram-history-dump#4]
I can't combine Test version of tg-cli + telegram-history-dump to dump anything. 

I can dump users and groups if I use the master tg-cli (without channels_backup - with channels_backup it unsurprisingly throws error)

but if I switch to the test branch of tg-cli... telegram-history-dump runs without throwing error including channels_backup but doesn't actually dump anything. 

I'm a newbie so I Followed suggestions [here] (https://github.com/vysheng/tg/issues/890?_pjax=%23js-repo-pjax-container) by @Polpetta / @vysheng - to install the test branch of telegram-cli 

suspect I'm making an obvious error somewhere - but as a newbie I can't find it...

**Comment by tvdstaaij** [comment]
The "problem" with tg's test branch (and the test/development branch of many projects in general) is that random things may break or change as a result of experimental commits. When I was testing the channel feature I had to try quite a few revisions in the test branch before I even found one that didn't trigger a build error. You can try building the revision that I successfully tested the channel feature with. Off the top of my head, you can use these steps to do so:
```bash
git clone --recursive https://github.com/vysheng/tg
git checkout c69f2a2326c1ebd078c4d90ab184b2b0bceff378
git submodule update --recursive
./configure && make
```

I don't know whether the problem you have with the tip of the test branch is temporary or structural, and I prefer to keep it that way unless there is a good reason to debug it. Once tg merges the channel feature into a release on master it's a different matter of course, I'll make sure it is compatible with master if the problem hasn't fixed itself by then.

**Comment by Polpetta** [comment]
@Humans-Huddle test branch is under developement so some feature may not work correctly or may missing! This is why channel's feature are not in the stable branch :blush:. I don't know when support for channels will be complete.

P.S.: If this solve your problem close this issue please! :blush:

**Comment by Humans-Huddle** [comment]
Thanks guys, appreciate the responses.
