### ISSUE TITLE
Selectively exclude channels

### ISSUE THREAD

**Issue by tecknojock** [tvdstaaij/telegram-history-dump#40]
It would be nice if one could also opt out of channels rather than opting into them.  Say you want every group you're in except for one really large group that gets 2k+ messages a day. Instead of having to manually add each one, it'd be nice to just exclude the big one(s) so that you dont miss new groups.

**Comment by tvdstaaij** [comment]
Thanks for your suggestion. I'll consider blacklisting for v3.x.

**Comment by tvdstaaij** [comment]
Fixed through #94.
