### ISSUE TITLE
telegram-history-dump.rb:9:in `require_relative': cannot load such file  ../dumpers/json

### ISSUE THREAD

**Issue by atenrok** [tvdstaaij/telegram-history-dump#41]
trying to use your script but this is all I get.

$ ruby telegram-history-dump.rb
telegram-history-dump.rb:9:in `require_relative': cannot load such file -- (path to ruby script)/dumpers/json (LoadError)
        from telegram-history-dump.rb:9:in`<main>

Please help

**Comment by tvdstaaij** [comment]
I cannot reproduce this with the latest master revision and latest Ruby stable (2.3.1). I recommend checking your filesystem permissions. No idea what else could cause this; require_relative is always relative to the script file so the path should be good.
