### ISSUE TITLE
unexpected token (JSON::ParserError)

### ISSUE THREAD

**Issue by ZombieTheBest** [tvdstaaij/telegram-history-dump#44]
Hi!
I've been using this tool for a while without any issue until yesterday. 
When i launch telegram-history-dump program quits with this exception right after connecting to telegram-cli:

```
/usr/lib/ruby/2.1.0/json/common.rb:155:in 'parse': 757: unexpected token at User *one_name*: 0 unread (JSON::ParserError)

from /usr/lib/ruby/2.1.0/json/common.rb:155:in parse
from telegram-history-dump.rb:37:in <main>
from telegram-history-dump.rb:278:in <main>
```
*one_name*: a Telegram Name, always the same one 

How can I fix this?
Thank you!

**Comment by tvdstaaij** [comment]
Are you sure you are launching telegram-cli with the `--json` argument?

**Comment by ZombieTheBest** [comment]
Can I say I'm an idiot? I was writing -json instead of --json. I'm sorry, shame on me.
