### ISSUE TITLE
Exception: Channel_list

### ISSUE THREAD

**Issue by tommylux** [tvdstaaij/telegram-history-dump#45]
Running for the first time, I get "can not find command 'Channel_List'"

Has this been removed by Telegram-CLI?

**Comment by tvdstaaij** [comment]
What version/revision of telegram-cli are you using? The telegram-cli master branch hasn't been updated since March, and the channel_list command exists in that revision. But it is a relatively recent addition to telegram-cli, so using an old revision may explain this.

**Comment by tommylux** [comment]
I rarely use Linux and had trouble cloning the branch, so took a copy from elsewhere. I installed Git and managed to clone the branch and a few other bits and pieces now have it working.

One thing to mention is that the commands don't seem to work properly when you have loaded the telegram-cli, but seem to work when you construct the command as part of the command line.

But I managed to get it working for my needs, so I was quite amazed at myself!
