### ISSUE TITLE
dumping channel has no author/user associated with the messages

### ISSUE THREAD

**Issue by jachin** [tvdstaaij/telegram-history-dump#48]
When I dump a channel there's no author associated with any of the messages.

When I look at the jsonl file there is a `"to"` and `"from"` for each message but it looks like it's just the channel. Which sounds weird, but the "from" -> "id" matches the channel's ID.

`"from":{
"id":"$050000008e0df13b169d06XXXXXXXX",
"peer_type":"channel",
"peer_id":XXXXXXXXX,
"print_name":"XXXXXXXXX",
"flags":65601,
"title":"XXXXXXXX",
"participants_count":0,
"admins_count":0,
"kicked_count":0
},
"to": the same,`

Poking around the telegram-cli I'm able to see the list of users in the channel, but when I run something like `history my_channel_name` I get the same thing (channel ID where I think should be getting the actual user who sent the message).

Is this a bug in telegram-cli? If so, does anyone know of a work around? If that's all it is maybe this could go on your list of known issues.

(And this is a wonderful little utility, thanks so much, even with the issues I've had, it's saved me a lot of time.)

**Comment by jachin** [comment]
Doh... I just found my answer. Turns out I want to do something that's currently not supported. Oh well.

https://telegram.org/faq_channels#q-how-do-i-know-who-posted-a-message

**Comment by tvdstaaij** [comment]
Mentioning @petrohs because based on their fork I believe they are trying to achieve the same thing.
