### ISSUE TITLE
Formatters doesn't detect service 'chat_add_user_link' action.

### ISSUE THREAD

**Issue by kiddick** [tvdstaaij/telegram-history-dump#50]

**Comment by tvdstaaij** [comment]
Hadn't seen this one before, did a search through my personal history dump and found exactly one entry. Apparently this means the founder of a group created an invite link that can be used to join the group without being explicitly added.

Do you believe this is significant enough to include in formatted output, and if so, do you have a proposal for how it should appear in the output?

**Comment by kiddick** [comment]
According to https://github.com/telegramdesktop/tdesktop/blob/d2e27726caaa82cff050d4d38703f803ebeee133/Telegram/Resources/langs/lang.strings#L568

that means that someone joined via link

**Comment by tvdstaaij** [comment]
You're absolutely right, I misinterpreted my history. This is indeed important. I just committed some formatter additions, I believe that should take care of this issue.
