### ISSUE TITLE
Invalid JSON

### ISSUE THREAD

**Issue by TPei** [tvdstaaij/telegram-history-dump#51]
Hey, this produces invalid json files with multiple root elements. Is this intentional?
Makes automatic parsing of the output files impossible...

**Comment by tvdstaaij** [comment]
Yeah, this is intentional. The output is according to the [JSON Lines](http://jsonlines.org/) spec. Basically it means you should process each line as a separate JSON object.

**Comment by TPei** [comment]
Yeah, sorry, I wasn't familiar with JSON Lines. Not the worst actually :D
