### ISSUE TITLE
Automaticallly Updating the Progress.json

### ISSUE THREAD

**Issue by Alexa69** [tvdstaaij/telegram-history-dump#65]
Hi

First of all thank you for all work ..

my problem is I would like to be able to toggle select between downloadable items ( Image/Video/ .. ) but don't start from the beginning use the contents already available in cache ..

just imagine I attempted to download channel "ABC" just TEXT .. after that I would like to re-download the channel but this time download the images too ... in this case it just download the same previous "TEXT" download .. not IMAGES unless I clean up the download folder remove the progress JSON and the rest this time it grabs TEXT + IMAGES too ...

could you add this capability to program to resolve this problem .. it's really painful to re-download a channel again because you just forgot to add images to download ...

**Comment by tvdstaaij** [comment]
To clarify the role of progress.json, it just tracks the point where the last dump ended so the script can continue from there on its next run. It does not store anything about the options used in the past, and messages before that point are not touched again even if options change. This does not apply to formatter options (the chats are re-formatted from the beginning on every run), but it does apply to media download options. Keep in mind that the dumps are simple line-based log files -- it's not anything like a randomly accessible message cache database.

So if you have dumped a dialog without media downloads and later decide that you want the media after all, the only way is to re-dump the entire dialog from start. It would be possible to hack in retroactive media downloading based on existing JSONL files, but this would be ugly and add too much complexity. You could try doing so yourself if you really want to, but I won't add such a feature to the codebase.

Doing this properly would require an actual database of messages, which is beyond the mission of this project of being a straightforward history dumper.

**Comment by Alexa69** [comment]
Yes, you are right .. the easiest way is to download everything from the beginning so later it just grabs the new messages ..
