### ISSUE TITLE
Grabbing Stickers

### ISSUE THREAD

**Issue by Alexa69** [tvdstaaij/telegram-history-dump#66]
is there any possible way to download the Stickers inside the conversations ?

for the emojis new browser upgrade transforms the UTF-8 Emojis to telegram similar looking Emojis .. However I am working on a way using Javascript to convert the UTF-8 to same exact Emojis which available on telegram .. I will definitely share it here

**Comment by tvdstaaij** [comment]
Have you tried enabling document downloads? If I recall correctly telegram-cli treats stickers as the `document` media type, and they will be webp files (Google's image format).

**Comment by Alexa69** [comment]
You are right , if I grab documents it grabs the stickers with .WEBP format, as today ONLY Google Chrome will display the .WEBP files .. WEBP is not available on FIREFOX , YET ( Which I was using )
