### ISSUE TITLE
Name too long - ignoring it

### ISSUE THREAD

**Issue by Akamaru** [tvdstaaij/telegram-history-dump#7]
i want to download everything except 1 group, because his name is too long (261 chars)
is it possible to ignore some groups/chats?

**Comment by tvdstaaij** [comment]
First of all, let me observe a moment of silence in amazement that people have Telegram group names longer than 2^8 characters. :expressionless: 

As for the solution, I'd rather fix this by truncating the group names to a reasonably safe length. I did this with the commit referenced above this comment. You can try it by either applying this particular change to your local copy, or by switching to the development branch (`git checkout dev`). Note that the development version has a new config file syntax.

**Comment by Akamaru** [comment]
I changed the local files and it worked perfectly thx
