### ISSUE TITLE
Unexpected message ID length (0)

### ISSUE THREAD

**Issue by zhangyubaka** [tvdstaaij/telegram-history-dump#72]
msg_id.rb:28:in `assert_length': Unexpected message ID length (0). Please report this as an issue if your telegram-cli is up to date. (RuntimeError)
Using latest telegram-cli on macOS,ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]

**Comment by tvdstaaij** [comment]
Thanks for reporting, should be fixed by the above commit.

**Comment by zhangyubaka** [comment]
Still appear in latest.

**Comment by tvdstaaij** [comment]
You're right, that fix wasn't enough. I did it based on a hunch because I could not reproduce the issue myself. This time I created a fake test message with an empty id for testing; should really be fixed now!
