### ISSUE TITLE
unexpected token at 'ChannelName'

### ISSUE THREAD

**Issue by Jimmm** [tvdstaaij/telegram-history-dump#90]
The first run was OK, the second gives me this error:

ruby telegram-history-dump.rb
I, [2017-10-15T00:29:21.021925 #37]  INFO -- : Attaching to telegram-cli control socket at localhost:9009
/usr/lib/ruby/2.3.0/json/common.rb:156:in `parse': 784: unexpected token at 'Channel Telegram Info Чат: 85 unread (JSON::ParserError)
'
        from /usr/lib/ruby/2.3.0/json/common.rb:156:in `parse'
        from telegram-history-dump.rb:48:in `exec_tg_command'
        from telegram-history-dump.rb:322:in `<main>'

**Comment by Jimmm** [comment]
I used another telegram account, same problem.

**Comment by ColVosch** [comment]
starting telegram-cli with --json parameter fixed it for me. Hope this helps!

**Comment by Jimmm** [comment]
I love you!
I saved all steps in a telegram chat and the messengers' formatting engine replaced --json with  —json
